//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipe
    {  
        public int id { get; set; }
        public string designation { get; set; }
        public Nullable<System.TimeSpan> dateDebut { get; set; }
        public Nullable<System.TimeSpan> dateFin { get; set; }
    }
}
