//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PiloteFini
    {  
        public string matricule { get; set; }
        public string nom { get; set; }
        public string poste { get; set; }
        public string UF { get; set; }
        public string module { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idLigne { get; set; }
        public int id { get; set; }
    }
}
