//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValOKdIntegrtion
    {  
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> ok { get; set; }
        public Nullable<bool> nok { get; set; }
        public Nullable<bool> na { get; set; }
        public Nullable<int> idDescription { get; set; }
        public Nullable<int> idLigne { get; set; }
        public string commentaire { get; set; }
        public string equipe { get; set; }
    
        public virtual OKDesription OKDesription { get; set; }
    }
}
